### ISSUE TITLE
Write docs, extract DOBT params to config vars

### ISSUE THREAD

**Issue by ajb** [dobtco/screendoor-nps#1]

**Comment by ajb** [comment]
@kariannemah: now that we've done this process a couple times, I feel confident saying that Screendoor is pretty darn good for collecting NPS.

(Although... calculating the average automatically would be nice. Maybe I should add a script? heh.)

If I write up some docs, do we want to blog about this? I can take a crack at it from an engineering perspective, but maybe it would be more interesting if you published something from the CS angle.

**Comment by ajb** [comment]
cc @beccamoore above ^

**Comment by beccamoore** [comment]
@ajb: I love both angles. I think that the posts we've done in the past along these lines have been really interesting and add a lot of texture to our content. (Like the OpenRFPs and Making Bootstrap Accessible posts.)

One thought I've had is that we might want to "house" these separately from our Rewiring Government/GovTech articles. (The content is extremely valuable, but probably to a different audience than our customers fit into.) This is definitely something we'll have to think through in the blog redesign.

**Comment by ajb** [comment]
Hm, yeah, maybe it's a team decision, but I think that the Rewiring Government brand can cover both "rewiring" on a non-technical level, as well as rewiring from an engineering perspective -- it's just a matter of creating a distinction between the two in our category listings.

I'm happy to write a draft that details how we used the Screendoor API. I'll keep this assigned to me.

**Comment by beccamoore** [comment]
Ooh, I like that. I'll toy around with some wording that could marry those two ideas. Making that clear could be as easy as a clever subtitle for the blog and some tagging/design help to nudge people toward the content that suits them.

**Comment by ajb** [comment]
I wrote a proper README: https://github.com/dobtco/screendoor-nps

I think this will work as a starting point for the blog, so I opened a PR there: https://github.com/dobtco/blog-v2/pull/152
